version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password1234
      MYSQL_DATABASE: grab_the_shovel
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php_backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_API_URL=http://localhost:80/api/
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge